name: heracleum
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - dataclass-csv
    - flwr[simulation]
    - flwr-datasets[vision]
    - scikit-learn
    - torch
    - torchvision